### ISSUE TITLE
无法转换，程序卡死错误

### ISSUE THREAD

**Issue by 2000PJL** [ruhuang2001/EasyCartoon#2]
你好，请问你这使用python3写的吗？我根据我的文件情况修改后，出现一直无法转换的错误，程序卡死，使用键盘中断程序后，系统抛出了如下错误：
Traceback (most recent call last):
  File "E:\软件备份\手机端的\EasyCartoon-main\main.py", line 73, in <module>
    main()
  File "E:\软件备份\手机端的\EasyCartoon-main\main.py", line 69, in main
    imageToPdf(cartoon_pdf)
  File "E:\软件备份\手机端的\EasyCartoon-main\main.py", line 55, in imageToPdf
    c.drawImage(i, 0, 0, w, h)
  File "D:\Python\Python3.10\lib\site-packages\reportlab\pdfgen\canvas.py", line 990, in drawImage
    imgObj = pdfdoc.PDFImageXObject(name, image, mask=mask)
  File "D:\Python\Python3.10\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 2084, in __init__
    self.loadImageFromA85(src)
  File "D:\Python\Python3.10\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 2092, in loadImageFromA85
    imagedata = pdfutils.makeA85Image(source,IMG=IMG,detectJpeg=True)
  File "D:\Python\Python3.10\lib\site-packages\reportlab\pdfbase\pdfutils.py", line 49, in makeA85Image
    compressed = zlib.compress(raw)   #this bit is very fast...
KeyboardInterrupt

**Comment by ruhuang2001** [comment]
是Python3，我有一段时间没用了不清楚包是否有更新的原因。
首先你确认一下你下载的漫画文件名是否和renamePre这个函数中的“_第×话”的格式，X是数字。如果不是这个格式请自行修改对应的前后缀。
另外确认一下是否安装好相关的包，文件路径是否有误。

**Comment by ruhuang2001** [comment]
如果尝试修改后仍有问题，可以使用邮件发送下载文件的文件名的截图给我或者在此issue下，我会在有空的时候回复你解决方法。（邮箱在Github主页）

**Comment by ruhuang2001** [comment]
@2000PJL README添加了使用方法，可以尝试看看能否运行。

**Comment by ruhuang2001** [comment]
hi看到这个issue较长时间没有回复，猜测问题应该已经解决了。如果仍有任何欢迎使用邮件联系我，这边先 close 了
